image: generic-c

before_script:
  - git clone https://github.com/Microsoft/vcpkg.git --depth=1
  - sh ./vcpkg/bootstrap-vcpkg.sh
  - vcpkg/vcpkg install fmt

build:
  script:
    - cmake -B build -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
    - cmake --build build
